Repository gardener/inventory, pull requests merged in 2025-04, with the labels that each got.

#409 Openstack orphan server
  internal/pkg/migrations/20250327071100_openstack_orphan_server.tx.down.sql
  internal/pkg/migrations/20250327071100_openstack_orphan_server.tx.up.sql
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/xs

#417 OpenStack orphan LoadBalancer view
  internal/pkg/migrations/20250403113303_openstack_orphan_loadbalancer.tx.down.sql
  internal/pkg/migrations/20250403113303_openstack_orphan_loadbalancer.tx.up.sql
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/xs

#419 OpenStack Auth documentation
  docs/auth-openstack.md
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/s

#426 deps: bump golangci-lint to v1.64.8
  Makefile
Labels: reviewed/ok-to-test, reviewed/lgtm, size/xs

#429 Fix subnet and network descriptions in OpenStack dashboards
  deployment/kustomize/grafana/config/files/dashboards/inventory/inventory-leaked-openstack.json
  deployment/kustomize/grafana/config/files/dashboards/inventory/inventory-openstack.json
  extra/grafana/dashboards/inventory/inventory-leaked-openstack.json
  extra/grafana/dashboards/inventory/inventory-openstack.json
Labels: needs/ok-to-test, needs/review, size/xs

#436 deployment/kustomize/worker: set `allowPrivilegeEscalation: false`
  deployment/kustomize/worker/deployment.yaml
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/xs

#437 core/config: `Parse` ignores empty paths
  pkg/core/config/config.go
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/xs
