Repository gardener/inventory, pull requests merged in 2025-07, with the labels that each got.

#550 Filter OpenStack projects by name
  pkg/openstack/tasks/projects.go
Labels: needs/review, size/xs

#553 deps: replace gopkg.in/yaml.v3 with goccy/go-yaml
  go.mod
  go.sum
  pkg/core/config/config.go
  pkg/utils/asynq/asynq.go
Labels: reviewed/lgtm, size/xs

#564 Openstack worker volume panel
  deployment/kustomize/grafana/config/files/dashboards/inventory/inventory-worker-openstack-tasks.json
  extra/grafana/dashboards/inventory/inventory-worker-openstack-tasks.json
Labels: needs/review, size/m

#562 update docs for openstack auth
  docs/auth-openstack.md
Labels: reviewed/lgtm, size/xs

#566 Fix rollback (down) migration for volumes
  internal/pkg/migrations/20250715110847_add_openstack_volume.tx.down.sql
Labels: reviewed/lgtm, needs/review, size/xs

#565 deps: update bun/extra/debug to v1.2.15
  go.mod
  go.sum
Labels: reviewed/lgtm, size/xs
